# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# A lot of this came from
# https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # Must match production node environment on Heroku
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache `./node_modules`
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache `./next/cache`
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        run: yarn install

      - name: Lint with Prettier
        run: yarn run lint

        ########################################################################
        # Optional Typescript Strict Type Checking
        #
        # Wow... There is a finely nuanced difference between a pull_request
        # event and a push event, I believe the pull request event happens only
        # at the time of pull request creation.  Pushing to a branch that is
        # part of a pull request is just a push event. Here's a easy to see
        # what data you have access to in the github context:
        #
        #    - name: GitHub Context
        #      env:
        #        GITHUB_CONTEXT: ${{ toJSON(github) }}
        #      run: echo "$GITHUB_CONTEXT"

      - name: Extract Head Ref Branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check Typescript
        if: ${{ startsWith('ts-', $HEAD_BRANCH) || contains('typescript', $HEAD_BRANCH) }}
        run: yarn run types:strict
        env:
          HEAD_BRANCH: ${{ steps.extract_branch.outputs.branch }}

        ########################################################################

      - name: Build with NextJS
        run: yarn run build
