name: Staging Deploy
on: 
  push:
    branches: ['staging', 'dockerize']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and Deploy
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
        # uses: akhileshns/heroku-deploy@v3.12.12
        # with:
        #   heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #   heroku_email: ${{secrets.HEROKU_EMAIL}}
        #   heroku_app_name: "upward-staging"
        #   usedocker: true